name: Yatin Calculator and Notify

on:
  schedule:
    - cron: '30 1,2,4,7,11,16,22 * * *'
  workflow_dispatch:  # 手動での実行を許可

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run Yatin Calculator Script
      env:
        LINE_NOTIFY_TOKEN: ${{ secrets.LINE_NOTIFY_TOKEN }}  # GitHub Secretsからトークンを取得
      run: npm start
