name: Yatin Calculator and Notify

on:
  schedule:
    - cron: '30 1 * * *'  # 毎日9:00 AMに実行 (UTC)
    - cron: '32 2 * * *'  # 毎日9:00 AMに実行 (UTC)
    - cron: '34 3 * * *'  # 毎日9:00 AMに実行 (UTC)
    - cron: '36 4 * * *'  # 毎日9:00 AMに実行 (UTC)
    - cron: '38 5 * * *'  # 毎日9:00 AMに実行 (UTC)
    - cron: '40 6 * * *'  # 毎日9:00 AMに実行 (UTC)
    - cron: '42 7 * * *'  # 毎日9:00 AMに実行 (UTC)
    - cron: '44 8 * * *'  # 毎日9:00 AMに実行 (UTC)
    - cron: '46 9 * * *'  # 毎日9:00 AMに実行 (UTC)
    - cron: '48 10 * * *'  # 毎日9:00 AMに実行 (UTC)
    - cron: '50 11 * * *'  # 毎日9:00 AMに実行 (UTC)
    - cron: '52 12 * * *'  # 毎日9:00 AMに実行 (UTC)
    - cron: '54 13 * * *'  # 毎日9:00 AMに実行 (UTC)
    - cron: '56 14 * * *'  # 毎日9:00 AMに実行 (UTC)
    - cron: '58 15 * * *'  # 毎日9:00 AMに実行 (UTC)
    - cron: '10 16 * * *'  # 毎日9:00 AMに実行 (UTC)
    - cron: '12 17 * * *'  # 毎日9:00 AMに実行 (UTC)
    - cron: '14 18 * * *'  # 毎日9:00 AMに実行 (UTC)
    - cron: '16 19 * * *'  # 毎日9:00 AMに実行 (UTC)
    - cron: '18 20 * * *'  # 毎日9:00 AMに実行 (UTC)
    - cron: '10 * * * *'
  workflow_dispatch:  # 手動での実行を許可

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run Yatin Calculator Script
      env:
        LINE_NOTIFY_TOKEN: ${{ secrets.LINE_NOTIFY_TOKEN }}  # GitHub Secretsからトークンを取得
      run: npm start
